const props = {
  base: [{
    value: 'name',
    label: '姓名',
    required: true
  }, {
    value: 'cardid',
    label: '证件号码',
    required: true,
    validator: [{
      pattern: /^\d{6}(((19|20)\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])\d{3}([0-9]|x|X))|(\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])\d{3}))$/,
      message: '证件号码错误'
    }]
  }, {
    value: 'birthday',
    label: '出生年月',
    readonly: true,
    notSubmit: true
  }, {
    value: 'age',
    label: '年龄',
    readonly: true,
    notSubmit: true
  }, {
    value: 'sex',
    label: '性别',
    required: true,
    type: 'combobox'
  }, {
    value: 'phone',
    label: '手机号码',
    required: true,
    validator: [{
      pattern: /^[1]([3-9])[0-9]{9}$/,
      message: '手机号码格式错误'
    }]
  }, {
    value: 'email',
    label: '邮箱',
    required: true,
    validator: [{
      type: 'email',
      message: '邮箱格式错误'
    }]
  }, {
    value: 'address',
    label: '联系地址',
    required: true
  }],
  edu: [{
    value: 'education',
    label: '学历',
    required: true,
    type: 'combobox'
  }, {
    value: 'school',
    label: '毕业学校',
    required: true
  }, {
    value: 'major',
    label: '所学专业',
    required: true
  }, {
    value: 'political',
    label: '政治面貌',
    required: true,
    type: 'combobox'
  }],
  job: [{
    value: 'location',
    label: '所属省市区',
    required: true,
    isToString: true
  }, {
    value: 'type',
    label: '人员类型',
    required: true,
    type: 'combobox'
  }, {
    value: 'organization',
    label: '所属机构',
    required: true,
    type: 'combobox',
  }, {
    value: 'department',
    label: '所属部门',
    required: true,
    type: 'combobox',
    depend: 'type',
    force: 3
  }, {
    value: 'position',
    label: '现任职务',
    type: 'combobox',
    required: true,
    depend: 'type',
    force: 3
  }, {
    value: 'nature',
    label: '岗位性质',
    type: 'combobox',
    required: true,
    depend: 'type',
    force: 3
  }, {
    value: 'techtitle',
    label: '专业技术职称',
    depend: 'type',
    type: 'combobox',
    multi: true,
    force: 3
  }, {
    value: 'expertise',
    label: '审计特长',
    depend: 'type',
    type: 'combobox',
    multi: true,
    force: 3
  }, {
    value: 'workbegin',
    label: '参加工作年月',
    depend: 'type',
    type: 'datepicker',
    force: 3
  }, {
    value: 'auditbegin',
    label: '参加审计年月',
    depend: 'type',
    type: 'datepicker',
    force: 3
  }, {
    value: 'train',
    label: '业务培训情况',
    canplus: true,
    depend: 'type',
    force: 3
  }, {
    value: 'position',
    label: '职务',
    depend: 'type',
    not: 3
  }, {
    value: 'workbegin',
    label: '开始从业日期',
    depend: 'type',
    type: 'datepicker',
    required: true,
    not: 3
  }, {
    value: 'specialties',
    label: '专业特长',
    required: true,
    depend: 'type',
    not: 3
  }, {
    value: 'qualification',
    label: '专业技术资质',
    canplus: true,
    depend: 'type',
    not: 3
  }, {
    value: 'achievements',
    label: '近三年工作业绩',
    depend: 'type',
    not: 3
  }],
  other: [{
    value: 'comment',
    label: '备注'
  }, {
    value: 'role',
    label: '角色',
    type: 'combobox',
    multi: true,
    required: true
  }]
}

const tagList = {
  base: '基本信息',
  edu: '教育信息',
  job: '职能信息',
  other: '其他信息'
}

export {
  tagList,
  props
}
